import { User } from '../types';
import { supabase } from './supabaseClient';

// Helper to map DB columns (snake_case) to App types (camelCase)
const mapUserFromDB = (dbUser: any): User => ({
  id: dbUser.id,
  name: dbUser.name,
  email: dbUser.email,
  password: dbUser.password,
  isAdmin: dbUser.is_admin, // Note: DB column is is_admin
});

// Initialize default admin if no users exist in DB
export const initializeAuth = async (): Promise<void> => {
  try {
    const { count, error } = await supabase
      .from('app_users')
      .select('*', { count: 'exact', head: true });

    if (error) throw error;

    if (count === 0) {
      const { error: insertError } = await supabase.from('app_users').insert([
        {
          name: 'Administrador',
          email: 'admin@admin.com',
          password: 'admin123',
          is_admin: true,
        },
      ]);
      
      if (insertError) console.error('Error creating default admin:', insertError);
      else console.log('Default admin created in Supabase');
    }
  } catch (err) {
    console.error('Failed to initialize auth:', err);
  }
};

export const getUsers = async (): Promise<User[]> => {
  const { data, error } = await supabase
    .from('app_users')
    .select('*')
    .order('created_at', { ascending: true });

  if (error) {
    console.error('Error fetching users:', error);
    return [];
  }

  return data.map(mapUserFromDB);
};

export const saveUser = async (user: User): Promise<void> => {
  // Check if we are updating (user exists) or creating
  // Since UUIDs are generated by frontend in the current flow, we can check if ID exists
  const { data: existingUser } = await supabase
    .from('app_users')
    .select('id')
    .eq('id', user.id)
    .maybeSingle();

  const userData = {
    id: user.id,
    name: user.name,
    email: user.email,
    password: user.password,
    is_admin: user.isAdmin,
  };

  let error;
  if (existingUser) {
    // Update
    const { error: updateError } = await supabase
      .from('app_users')
      .update(userData)
      .eq('id', user.id);
    error = updateError;
  } else {
    // Insert
    const { error: insertError } = await supabase
      .from('app_users')
      .insert([userData]);
    error = insertError;
  }

  if (error) throw error;
};

export const deleteUser = async (id: string): Promise<void> => {
  const { error } = await supabase
    .from('app_users')
    .delete()
    .eq('id', id);

  if (error) throw error;
};

export const validateLogin = async (email: string, password: string): Promise<User | null> => {
  const { data, error } = await supabase
    .from('app_users')
    .select('*')
    .eq('email', email)
    .eq('password', password) // In production, never compare plain text passwords directly in query
    .maybeSingle();

  if (error || !data) {
    return null;
  }

  return mapUserFromDB(data);
};